### ISSUE TITLE
Examples of Surface don't work on laptop/chrome unless postEffect=true

### ISSUE THREAD

**Issue by MiltonCobo** [ecomfe/echarts-gl#386] opened 2021-01-23 12:12 UTC
I notice that the following example 

https://echarts.apache.org/examples/en/editor.html?c=simple-surface&gl=1

is not working in my personal laptop. Curiously it works on my ipad. In the laptop the visualMap.color is not showing:

![image](https://user-images.githubusercontent.com/44674476/105577729-609f9900-5d49-11eb-9071-121b5494615c.png)

If the background is made more dark, then the visualMap colorPalette shows. On the other hand, in hand-made examples
(usinng echarts 5.0.1 and echarts-gl 2.0.0),  the same issue appears but in this case darkening the background doesn't solve the problem, only setting postEffect to true works, but then the surface is not plotted in Mobile devices.

**Comment by pissang** [comment] 2021-01-24 06:02
It's so weird that it works on my laptop. Not sure if it's because I'm using the M1 MacBook pro

**Comment by pissang** [comment] 2021-01-24 06:36
Seems it's caused by the invalid alpha value. Just fixed in 2.0.1.

**Closed** 2021-01-24 06:38 UTC
